# Generated by Django 2.0b1 on 2019-12-11 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191209_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='addressedTo',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
